---
DEFAULT_VAGRANT_BOX: "vasatanasov/debian-11.3-docker"
DEFAULT_VAGRANT_BOX_VERSION: "202207.15.0"
CPUS_CONTROL_PANE_NODE: 2
CPUS_WORKER_NODE: 2
MEMORY_CONTROL_PANE_NODE: 2048
MEMORY_WORKER_NODE: 2048
WORKER_NODES_COUNT: 2
CONTROL_PLANE_COUNT: 1
IP_NW: "192.168.81."
IP_START: 210
POD_NETWORK: "10.244.0.0/16"
VAGRANTFILE_API_VERSION: "2"
SHARED_DIR: "/home/vagrant/shared"
SCRIPTS_PATH: "/tmp" # The location where vagrant will upload the scripts on the guest

DEFAULT_KUBERNETES_VERSION: "1.23.8-00"
